services:
  - type: web
    name: file-manager-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    rootDirectory: .
    envVars:
      - key: NODE_ENV
        value: production