services:
  - type: web
    name: file-manager-backend
    env: node
    buildCommand: npm install
    startCommand: node --experimental-modules server.js
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"